# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12257d039a0789c8b449dab8140643c8c06a7c9f81190f1bfbf2743b5d2259676bab896080d5ea03f4e91f13d7b5548d5a19095e467dcbcaa817eea3f1eeff12

test:
  secret_key_base: 88fdf3983db27ea44c972303d06d1a0992be2b74807fecb72d9f729036887c311ed30fb5a0495cbeb5ddad33b754c3afff489f0e362bd6588186ca303323317d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
